/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hn

import com.google.gson.Gson
import hn.model.Story
import hn.model.StoryApi
import hn.network.NetworkUtils
import hn.util.JsonStorage
import hn.util.LogsStorage
import kotlinx.coroutines.*

private const val MAX_STORIES = 20

fun main() = runBlocking<Unit> {
    launch { // launch a new coroutine in the scope of runBlocking
        val apiInterface = NetworkUtils().getInstance()

        val topStories = mutableListOf<Deferred<Story>>()
        apiInterface.getTopStories().take(MAX_STORIES).forEach { id ->
            topStories.add(async { apiInterface.getStory(id) })
        }

        val topTenStories = topStories.awaitAll()
        val storyApiList = mutableListOf<StoryApi>() // This list is converted to JSON format
        val localStorage = LogsStorage()
        val jsonStorage = JsonStorage()

        localStorage.appendDate()
        topTenStories.forEachIndexed { index, story ->
            // Save this information along with the date and index in a txt file
            localStorage.saveString("${index + 1}. ${story.title}")
            storyApiList.add(StoryApi(story.id, story.title)) // Populating the list here
        }
        localStorage.close()

        jsonStorage.saveJson(Gson().toJson(storyApiList))
        jsonStorage.close()
    }
}
