/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hn

import hn.model.Story
import hn.network.NetworkUtils
import hn.util.LocalStorage
import kotlinx.coroutines.*

private const val MAX_STORIES = 10

fun main() = runBlocking<Unit> {
    launch { // launch a new coroutine in the scope of runBlocking
        val apiInterface = NetworkUtils().getInstance()

        val topStories = mutableListOf<Deferred<Story>>()
        apiInterface.getTopStories().take(MAX_STORIES).forEach { id ->
            topStories.add(async { apiInterface.getStory(id) })
        }

        val topTenStories = topStories.awaitAll()
        val localStorage = LocalStorage()
        localStorage.appendDate()
        topTenStories.forEachIndexed { index, story ->
            // Save this information along with the date and index in a txt file
            localStorage.saveString("${index + 1}. ${story.title}")
        }
        localStorage.close()
    }
}